server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
    #     搭建注册中心集群模式使用
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
    #    不把自己注册
    registerWithEureka: true
    #    不扫描自己
    fetchRegistry: true

  server:
    #      开启自我保护
    enableSelfPreservation: true
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000
spring:
  application:
    name: register-eureka